### ISSUE TITLE
[MAVEN] Missing Version 3.0.2

### ISSUE THREAD

**Issue by Kithio** [emilyploszaj/trinkets#109]
Been setting up my DevEnv for 1.17.1 and wanted to make use of Trinkets API but is running into problems running it with the same issue as shown in #106 because 3.0.1 and 3.0.2 are both missing from the maven repo, making me unable to get access to the update through gradle.

Any plans to push 3.0.2 to Maven or are you waiting for another version before you do so?

**Comment by emilyalexandra** [comment]
I've just been having issues pushing versions to the maven, they'll be up asap

**Comment by CammiePone** [comment]
Any update on this, or is the maven still causing problems?

**Comment by AcrobatTv** [comment]
yes,maven still causing problems
