### ISSUE TITLE
SlotGroup Mouseover displays when right-click equipped in creative

### ISSUE THREAD

**Issue by ItemCookie** [emilyploszaj/trinkets#11]
(Non-native speaker)
Trinkets equipped by right-clicking in creative while having the last tab selected to be a tab other than the survival inventory will make the tooltip display when opening the inventory (Persists through tab switches, inventory close and enter and disappears when selecting survival inventory)

Launcher: Intellij Idea (Development Environment)
Minecraft: 1.15.1
Fabric Loader: 0.7.2+build.175
Fabric API: 0.4.25+build.282-1.15
Trinkets: 2.3.0

Video: https://youtu.be/7w3I6mkv-5o
Image: [Down Below](https://user-images.githubusercontent.com/27014604/71486768-4464bc00-2818-11ea-8ca5-666f615346cc.png)
![Tooltip Bug](https://user-images.githubusercontent.com/27014604/71486768-4464bc00-2818-11ea-8ca5-666f615346cc.png)

**Comment by emilyploszaj** [comment]
This has been fixed in release v2.4.0
