### ISSUE TITLE
Shift clicking trinkets in creative inventory causes them to not work in survival.

### ISSUE THREAD

**Issue by toErIpNid** [emilyploszaj/trinkets#112]
Going into survival and trying to use and/or take off the trinkets shift-clicked from creative mode causes them to vanish. 

MC Version: 1.17.1
Fabric Version: 0.11.6
Trinkets Version: 3.0.2

Log: 
[latest.log](https://github.com/emilyalexandra/trinkets/files/6910250/latest.log)

**Comment by Gluton-Official** [comment]
In version 3.0.4, trinkets shift-clicked on in creative will not be rendered to other players.

**Comment by emilyploszaj** [comment]
Fixed in 3.2.0
