### ISSUE TITLE
Item in trinkets slot not showing to other players

### ISSUE THREAD

**Issue by vihangatheturtle** [emilyploszaj/trinkets#113]
Im using Give Me Hats! mod and the hats will only show for any other player on a multiplayer fabric 1.17 server if I relog. If I change the hat i am wearing i need to relog for the new hat to appear for them. Is this a trinkets issue or Give Me Hats!. There are no errors in console either when i switch hats. The 1.17.1 trinkets version doesnt work for 1.17

**Comment by apace100** [comment]
I'm the author of a cosmetic armor mod which uses Trinkets in 1.17.1, and one of the players has reported the same problem with my mod (cosmetic armor only syncing when a player relogs). I came here to look at the wiki to find any information about synchronizing the Trinkets information, but couldn't find any.

I'm not sure now whether this is something that's supposed to work out of the box and is buggy, or if the wiki is just missing information.

A clarification on this would be helpful and much appreciated. :)

**Comment by emilyalexandra** [comment]
as an author you should not have to do anything special, this currently seems to be either an issue with cardinal components or (more likely) an issue with how I'm using cardinal components

**Comment by emilyploszaj** [comment]
Officially squashed thanks to C4's work on #119
