### ISSUE TITLE
I cant see the extended slots which are normaly created in this mod the bug is sice i updated to 1.17

### ISSUE THREAD

**Issue by HobbyloserMensch** [emilyploszaj/trinkets#116]
https://user-images.githubusercontent.com/89376573/130400877-d9ae7760-d526-4541-beec-307453adf025.mp4

perhaps it is because of the other mods installed or i made a stupid mistake

**Comment by emilyploszaj** [comment]
trinkets 3.0.0 onward don't add the cape slot for elytra, this is a separate mod by c4
