### ISSUE TITLE
Specify amount of items that can be put into a slot

### ISSUE THREAD

**Issue by KxmischesDomi** [emilyploszaj/trinkets#117]
It should be possible to specify in the `tags/items/[group]/[slot].json` file how many of each item can be put into the slot

**Comment by emilyploszaj** [comment]
This is incompatible with the tag schema, stack limiting should be done by the items themselves

**Comment by KxmischesDomi** [comment]
I'm using vanilla items and I only wan't players to put in one of it in the trinkets slot
