### ISSUE TITLE
Capes not working as expected

### ISSUE THREAD

**Issue by elhertz** [emilyploszaj/trinkets#118]
I'm using https://www.curseforge.com/minecraft/mc-mods/capes to render my optifine cape and when I use Trinkets it doesn't work as expected (I used the MinecraftCapes mod before and got the same problem).
I removed Elytra Trinket just in case and it seems it is a problem with Trinkets.

**Elytras showcased in the video:**
<ins>Minecraft Vanilla Elytra</ins> (the cape is not under the elytra but it doesn't render the cape on the elytra)
<ins>BetterEnd armored elytras</ins> (capes shouldn't render on a custom item like the armored elytra, also the cape is still showing under it)
<ins>Icarus Wings</ins> (the cape should become invisible when wearing the wings)

https://user-images.githubusercontent.com/13700335/131410176-486c12e1-dd80-4cff-8f9e-73bb0d06fda5.mp4

**Comment by emilyploszaj** [comment]
you seem to be using far too many mods to pin down this issue to trinkets, and notably, trinkets doesn't touch anything to do with cape or elytra rendering, this must be an issue with the other mods you're using, try using fewer mods to pin this down

**Comment by elhertz** [comment]
I'm sorry. I should've been more thorough with my investigation.
If trinket doesn't mess with capes then the common factor between Elytra Trinket and Icarus is the [Caelus API](https://www.curseforge.com/minecraft/mc-mods/caelus-fabric)

https://user-images.githubusercontent.com/13700335/131435121-1f9a0cc2-78ec-4c30-a2cd-b064ecc96895.mp4


https://user-images.githubusercontent.com/13700335/131435178-34a8a7db-8912-4f88-b165-95a122fdfd94.mp4

Then for the better end armored elytra I think I should report it to them


https://user-images.githubusercontent.com/13700335/131435289-7a38606b-e6d7-4651-b623-05499d980bb8.mp4

As for the cape not rendering when the elytra was equipped in the chestplate slot I don't really know. It might be as you said, an issue with the other mods.
Could this also be FabricCapes' problem? I don't really know what to do. I don't wanna report the issue to everyone and cause a bigger problem.
