### ISSUE TITLE
Attributes are not correctly updated when trinkets are replaced

### ISSUE THREAD

**Issue by williewillus** [emilyploszaj/trinkets#120]
https://github.com/emilyploszaj/trinkets/blob/main/src/main/java/dev/emi/trinkets/mixin/LivingEntityMixin.java#L146

`oldStack` is passed to the new trinket instead of `newStack`

**Comment by emilyploszaj** [comment]
Good catch, fixed with [this commit](https://github.com/emilyploszaj/trinkets/commit/1606fc07adfcf68957bfb419e36f32085bed0f78), will be in a release hopefully later today with the visual desync bug fix.
