### ISSUE TITLE
Client Side Synchronisation

### ISSUE THREAD

**Issue by KxmischesDomi** [emilyploszaj/trinkets#128]
Currently the items in trinkets slots are only sent to other clients when logging in. 
It is possible to automatically update the items in the trinkets slots on the clients?

**Comment by TheIllusiveC4** [comment]
Which version of Trinkets are you using?

**Comment by KxmischesDomi** [comment]
3.0.2, I guess I should try the newest version before making an issue. I'm sorry xd

**Comment by KxmischesDomi** [comment]
Oh yep now it seems to work just fine. Sorry for the trouble ^^
