### ISSUE TITLE
1.17.1 instantly closes after starting with trinkets(any version of it)

### ISSUE THREAD

**Issue by Bernflex603** [emilyploszaj/trinkets#134]
everytime I start the mod, fabric api, cloth config and architectury minecraft instantly crashes and it doesnt even create a crash report, so i cant even say what exactly ist wrong?! Do you know what this might cause? 

btw. this hasnt ever happened with any other mod on my pc before
tested with 3.0.1, 3.0.2, 3.0.3, 3.1.0

**Comment by emilyploszaj** [comment]
I can't determine the cause without a crash report or a log, unfortunately.
