### ISSUE TITLE
Drop behaviour on player death doesn't match Vanilla

### ISSUE THREAD

**Issue by Plecra** [emilyploszaj/trinkets#135]
https://github.com/emilyploszaj/trinkets/blob/cf5bd7250a305585ca718af42faba22ed6f80078/src/main/java/dev/emi/trinkets/mixin/LivingEntityMixin.java#L112

There is a separate method for players that provides the spewing behaviour around where the player died, and also sets the pickup delay to longer (2s instead of the current 0.5s) giving other players the chance to decide whether they're picking the items up.

I'm... not sure if I should give the name of the right method? I guess it'd have to be included in a PR that implemented this, so this is the one: `PlayerEntity.dropItem(itemStack, true, false)`

**Comment by emilyploszaj** [comment]
Fixed in 3.2.0
