### ISSUE TITLE
Optifine CIT Resourcepack Fails to load On trinket Slots

### ISSUE THREAD

**Issue by PhantomLeopard** [emilyploszaj/trinkets#139]
I have my own Resourcepack that I use for my own textures, which utilises both item and model textures, through Optifine CIT. However, I think that all items placed in the trinket slots, will not be able to have optifine cit textures. I was using the Elytra Trinkets mod, using the trinkets mod to make the elytra be able to be on at the same time as a chestplate. Now, this resourcepack worked perfectly under normal conditions, but when in a trinket slot, it converted back the vanilla model, as I think that Optifine CITs fail to render or something. Now, I think this IS a trinkets mod problem, as I have seen people on the elytra trinket mod comments saying the same thing, however I could be wrong. If you could fix this bug, (if it isn't a bug, could you please add it in a feature), that would be the best! Thanks!

Versions
Trinkets: trinkets-3.1.0
Elytra Trinket: elytratrinket-fabric-3.0.0-1.18.1

**Comment by emilyploszaj** [comment]
Model rendering for elytra should be the responsibility of elytra trinket, as far as I know. There is no way to add compatibility to optifine as a modder, and because of this and other reasons, I do not support it. Sorry
