### ISSUE TITLE
Mod + Elytra on vanilla servers broken

### ISSUE THREAD

**Issue by gbl** [emilyploszaj/trinkets#14]
When you're playing on a vanilla/spigot/paper server, and forget to disable the mod first, there are some optical glitches with trinkets (which don't really hurt much), but your Elytra won't work either even when it's in the chest (and not chest trinket) slot.

**Comment by emilyploszaj** [comment]
Trinkets isn't designed to be compatible with a vanilla server, I'm actually pretty surprised that's the only problem.
