### ISSUE TITLE
1.18.1 - crash rendering entity in world

### ISSUE THREAD

**Issue by bessiq** [emilyploszaj/trinkets#140]
Welp, I made some `observed:observer_lenses` from the mod Observed, and thought I'd try to place them in the face slot, and then what I guessed was the cosmetic head slot in Trinkets. The game did not like that, and now crashes a second or two after the world loads. I looked in the Observed jar file to confirm the glasses were not tagged for use in Trinkets, but the crash report shows them equipped in the cosmetic head slot (maybe anything can go there?). Crash report: [crash-2021-12-31_19.20.14-client.txt](https://github.com/emilyploszaj/trinkets/files/7797260/crash-2021-12-31_19.20.14-client.txt)
 
I can probably edit the player NBT data to remove the glasses, and/or try to temporarily remove Observed to see if it resolves the issue, but just wanted to let you know!

**Comment by emilyploszaj** [comment]
you have far too many mods for me to be able to pin this down as trinkets, and the stack trace doesn't suggest it, whatever's allowing everything in slots and doing custom rendering made a mistake it looks like.
