### ISSUE TITLE
Item replace command

### ISSUE THREAD

**Issue by RunicPlays** [emilyploszaj/trinkets#146]
When using the item replace command, I’d like it to replace the item in a trinket slot. The names of the slots don’t seem to work. Is this a bug or are there special names in the commands?

**Comment by WolkenGang** [comment]
Did you figure it out? I also try to find working slot id.

**Comment by ryleu** [comment]
it should, in theory, be something like trinkets.chest.necklace for the necklace spot. i'm not sure if this has been implemented.

**Comment by emilyploszaj** [comment]
There is a new `/trinkets` command added in the latest release for this function
