### ISSUE TITLE
Trinket Slots not appearing

### ISSUE THREAD

**Issue by CreeperCoder63** [emilyploszaj/trinkets#147]
So I added Trinkets and the Elytra Trinket mod (https://www.curseforge.com/minecraft/mc-mods/elytra-trinket-fabric)
To my mod pack. I equipped a chest plate and tried to find the trinket slot for the Elytra, but no trinket slots appear when I hover over the armour slots. (Please tell me if I am missing something essential this is my first time using trinkets)

**Comment by ruddsix** [comment]
I use the curios in 16.5 and trinkets in 1.18. The only difference I can find mod-wise is the use of caelus API, which was a mod used specifically for elytra mechanics. It was discontinued after 1.17.

**Comment by emilyploszaj** [comment]
this would be an issue with the elytra mod, unless you have a proper log that indicates something is happening with trinkets. make sure you disable other mods to determine if there is an incompatibility
