### ISSUE TITLE
Occasional crash opening creative inventory

### ISSUE THREAD

**Issue by Alkiasan** [emilyploszaj/trinkets#149]
I'm assuming it's related to the new ability to edit trinkets in creative inventory
Log:

https://www.toptal.com/developers/hastebin/emuyupejoc.yaml

**Comment by busterbrown1999** [comment]
Another example of this https://paste.corebot.dev/siyevosiru.php

**Comment by Wolfy8198** [comment]
I've had this same issue. #153

**Comment by Alkiasan** [comment]
I don't have any datapacks that touch the slots, though.

**Comment by Wolfy8198** [comment]
Hm. And another difference is that mine always crashes with the slot datapack.
