### ISSUE TITLE
Server side client crash

### ISSUE THREAD

**Issue by LiviiYS** [emilyploszaj/trinkets#152]
Players have been freezing & crashing on my server all with an error that seems to link back to trinket

https://paste.ee/p/SufDQ

**Comment by emilyploszaj** [comment]
this is definitely an issue but it shouldn't be causing crashes since it's in an executed task, I'll look into it though

**Comment by LiviiYS** [comment]
> executed

The main issue is that peoples Minecraft instances just freeze

**Comment by emilyploszaj** [comment]
Not exactly sure what would be causing that truthfully, this method should not be called very frequently. Either way, it's been fixed in the main branch, I'll close this issue the next release I make.

**Comment by emilyploszaj** [comment]
Fixed in 3.3.0
