### ISSUE TITLE
Crash with Slot Datapack

### ISSUE THREAD

**Issue by Wolfy8198** [emilyploszaj/trinkets#153]
I have Trinkets and Rings of Ascension installed, and when I use the datapack you sent me before to have 3 ring slots, it works fine as long as I'm in survival. Once I open the "survival inventory" in creative, my game crashes. It only does this when I have the datapack enabled, though.
[crash-2022-02-25_14.04.47-client.txt](https://github.com/emilyploszaj/trinkets/files/8143661/crash-2022-02-25_14.04.47-client.txt)

**Comment by emilyploszaj** [comment]
I was unable to recreate this issue, there may be another mod causing it. For now, there's nothing I can do.

**Comment by Wolfy8198** [comment]
I just retried, and I found the logs file for it, so here that is
[latest.log](https://github.com/emilyploszaj/trinkets/files/8188895/latest.log)
.
