### ISSUE TITLE
Trinket#tick() is called twice per tick

### ISSUE THREAD

**Issue by vicen621** [emilyploszaj/trinkets#155]
I don’t know if this is intentional or not, as the javadoc says "in the client and server side", but it would be nice to call only once per tick just like Item#inventoryTick()

**Comment by emilyploszaj** [comment]
Twice per tick is a misrepresentation here, it is only called once per tick on the client, and only once per tick on the server. This manifests as 2 calls per tick, but not on the same item, on the unique representations of the client and server. If you want to do something on the logical server, you simply have to check if you're on the client.
