### ISSUE TITLE
Random crashes in the Nether

### ISSUE THREAD

**Issue by Timolino456** [emilyploszaj/trinkets#158]
The game crashes at random spots in the Nether. 
Playing on 1.18.0.
MultiMC shows this:
![image](https://user-images.githubusercontent.com/38137599/159165582-7fe8d9e3-0548-477c-a232-0fbea9b8c101.png)
Mod list (mods with .disabled are obviously not enabled):
![image](https://user-images.githubusercontent.com/38137599/159165657-c97ec674-c9bb-4996-918e-6f6833dba174.png)
![image](https://user-images.githubusercontent.com/38137599/159165691-ffdb1d8c-f4a4-4bc5-8337-2a85eab02fbc.png)
If you need any additional info, let me know.

**Comment by Flashfyre** [comment]
Also happened to me in overworld

**Comment by Flashfyre** [comment]
This appears to be fixed in this commit: https://github.com/emilyploszaj/trinkets/commit/549c2aa797faf4c13f3338e9976eb1df14d13291

But this fix has apparently not been made available to versions prior to 1.18.2. This is definitely a problem for people still on 1.18.1.

**Comment by emilyploszaj** [comment]
This was fixed in 1.18.2, and curseforge now has a custom release with the fix as a beta for 1.18.1, marking this closed.
