### ISSUE TITLE
crash in modded smp

### ISSUE THREAD

**Issue by Aokanaaa** [emilyploszaj/trinkets#160]
![image](https://user-images.githubusercontent.com/102984797/161588840-894bdf7d-a0ee-4947-8cdb-891e64f58c86.png)
![image](https://user-images.githubusercontent.com/102984797/161588907-1ba3343d-710c-4389-87d4-06fb6d489fda.png)
code de sortie = error code

My minecraft crashes when I try to join a minecraft server with a curseforge modpack 
(https://www.curseforge.com/minecraft/modpacks/wolfqueens-origins)

before I could play without any issues but since 4 days I can't connect

the log when I connect to the server 
![image](https://user-images.githubusercontent.com/102984797/161589339-191698be-0763-4b50-87c4-625a53d01143.png)

Can someone help me ? ;-;

**Comment by Aokanaaa** [comment]
there's that before the big red block 
![image](https://user-images.githubusercontent.com/102984797/161589742-04fb9f96-9b14-4294-8b28-f032b4887cbd.png)

**Comment by itsdinkd** [comment]
> there's that before the big red block ![image](https://user-images.githubusercontent.com/102984797/161589742-04fb9f96-9b14-4294-8b28-f032b4887cbd.png)

This occurs quite often with origins. They do not cause crashes.
