### ISSUE TITLE
Trinket data not loading or syncing or *something*

### ISSUE THREAD

**Issue by LemmaEOF** [emilyploszaj/trinkets#170]
We're running into an issue on the BlanketCon server where no player has any trinket slots. At all. There are no logs indicating why this might be happening, whether it's an issue with loading data or sending it to clients, or *anything* else. We're on Trinkets 3.3.0 with multiple Trinket adding mods in the pack (primarily Botania). Pack and server are available in the BlanketCon organization discords.

**Comment by TheIllusiveC4** [comment]
Does this happen only on a server/multiplayer or also in single player?

**Comment by LemmaEOF** [comment]
I've had my hands too full with all the other pack stuff to test

**Comment by unascribed** [comment]
It's also happening in singleplayer.

Earlier versions of the pack didn't have this issue; I'm trying to isolate a culprit.

**Comment by emilyploszaj** [comment]
Weird mod combos have caused trinkets to not function in the past. Stuff that doesn't even touch trinkets. I assume it has something to do with data loading or packets, but I haven't had the time to look into it.

**Comment by unascribed** [comment]
I have the game in a debugger now and am looking into it.

**Comment by unascribed** [comment]
It's caused by the Server Translations API.

It causes the slot loaders in Trinkets to simply not be called; nothing to do with packets, the data just is never loaded.

**Comment by unascribed** [comment]
Specifically, this beautiful mixin, containing an unconditional cancel: https://github.com/arthurbambou/Server-Translations/blob/1.18.2/api/src/main/java/fr/catcore/server/translations/api/mixin/DataPackContentsMixin.java

The mixin is new in the 1.18.2 port.

**Comment by LemmaEOF** [comment]
Why are they cancelling, it Mixin passes that list by reference

**Comment by LemmaEOF** [comment]
also doesn't fabric literally have a hook for this so they don't need to break everyone else's RRLs

**Comment by unascribed** [comment]
Yes and yes

**Comment by unascribed** [comment]
The list returned in that method is constructed via List.of, so it's immutable. A copy is actually necessary.

**Comment by LemmaEOF** [comment]
Oh it actually looks like Fabric uses a transitive access widener now - I've filed an issue on their repo

**Comment by MaliciousZoroark** [comment]
Wait what broken mod was it? I'm wondering cause I'm suffering the exact same issue

**Comment by emilyploszaj** [comment]
Server Translations, posted higher up in the chain, it should've been updated by now
