### ISSUE TITLE
How would i get trinkets to be compatible with the Backslot mod?

### ISSUE THREAD

**Issue by 444wa** [emilyploszaj/trinkets#172]
Hello, so sorry if this is an incredibly easy solution and I am just overthinking it, but I have been scratching my head about this for a couple of hours unable to find the solution.  Long story short, I had recently played a modpack called 'Medieval Minecraft' that is incredibly well put together, and they had somehow got the Trinkets mod and Backslot mod to work well together, and the UI looks amazing like this. 
![image](https://user-images.githubusercontent.com/104756144/166200789-6ebae9a3-b631-4f9d-935c-a07e4f7fb5e9.png)
I am trying to make my own modpack and am trying to get these two mods to be compatible as well, just like that, but it is just not working out and I am not sure what I am doing wrong. I am positive I am most likely missing something, but I have no idea what it is. Any input would be greatly appreciated. I tried copy and pasting all sorts of api's I thought would work, and aside from the base mods, I am not sure what else I need for my modpack to have what this medieval modpack has. As in, these two mods being compatible. Thank you for reading

**Comment by emilyploszaj** [comment]
BackSlot is incompatible with Trinkets by nature of adding extra slots to the screen without using Trinkets. This is an issue the devs need to solve and I cannot. I believe most modpacks just use the config to move the slots around to a place trinkets doesn't put slots.
