### ISSUE TITLE
[1.18.2 Fabric] Opening the Creative Inventory menu after doing /reload with KubeJS crashes the game.

### ISSUE THREAD

**Issue by PaulZappia** [emilyploszaj/trinkets#175]
I'm making my own modpack and I wanted to use KubeJS to add in custom textures and recipes, however after using /reload to test out my new recipes, my game crashed. I even took off any mods that added trinket slots to the GUI and it still didn't help.
When I tested it without KubeJS, the problem pretty much went away.

Here is a crashlog as well as a video of the bug:
https://crashy.net/GyKKbO4OQSmlEdbERVq2
https://drive.google.com/file/d/1l2wqYVgc7wT5ZC9Xa1v_jwPcHo0Mmwgq/view?usp=sharing

**Comment by JuceDoesThings** [comment]
Same issue here, except with me it even happens without KubeJS. Makes it VERY hard to work on my datapacks without switching to client mods only when working with datapacks, especially more extensive ones
