### ISSUE TITLE
Language Based Slot Names

### ISSUE THREAD

**Issue by gudenau** [emilyploszaj/trinkets#18]
It would be good if the slots could use the language system that Minecraft has. It would allow for localization and better naming that automatically picking a name based off of the slot identifier.

A language file for en_us might look something like:
```JS
{
    "trinkets.slot.chest.cape": "Cape",
    "trinkets.slot.chest.necklace": "Necklace",
    "trinkets.slot.feet.aglet": "Aglet",
    "trinkets.slot.hand.ring": "Ring",
    "trinkets.slot.hand.gloves": "Gloves",
    "trinkets.slot.head.mask": "Mask",
    "trinkets.slot.legs.belt": "Belt",
    "trinkets.slot.offhand.ring": "Ring"
}
```

This won't make much of a difference for English speaking users, but for everyone else it would be a good feature.

**Comment by emilyploszaj** [comment]
This was something I considered but I've decided to wait until the 1.16 jump to make a change like that.

**Comment by emilyploszaj** [comment]
This has been done in the latest release
