### ISSUE TITLE
Trinket Slots don't appear on Quilt

### ISSUE THREAD

**Issue by RealSonarX** [emilyploszaj/trinkets#181]
Trinkets Version : 3.3.0

Expected Behaviour : The slots to be visible and for me to be able to equip items in them.

Behaviour : They do not appear to load.
Modloader : Quilt 0.17.0

**Comment by emilyploszaj** [comment]
I have personally seen Trinkets loading on Quilt along side Botania and a couple hundred other mods, what does your mod list look like, are you possibly introducing some incompatibilities?

**Comment by MaliciousZoroark** [comment]
My modlist is quite large.

![image](https://user-images.githubusercontent.com/80487755/171662355-fd51e4ad-78bf-4d1d-b13b-aa165924d834.png)

![image](https://user-images.githubusercontent.com/80487755/171662481-3bfc54e6-f440-4477-815c-4d9d65092991.png)

![image](https://user-images.githubusercontent.com/80487755/171662529-04aed37d-9eaa-48fa-9996-b43d4a44266d.png)

![image](https://user-images.githubusercontent.com/80487755/171662576-9de37081-b0f2-4404-8cc2-3e29fb6c999a.png)
![image](https://user-images.githubusercontent.com/80487755/171662625-da9e7e29-ecd0-4efc-9f04-4668ef0924c8.png)

**Comment by MaliciousZoroark** [comment]
https://paste.ee/p/Mco9T here are my logs too if you can see anything

**Comment by MaliciousZoroark** [comment]
Ah alright. Is there anything you can tell me that would help me find which pair? Any keywords in logs?

**Comment by emilyploszaj** [comment]
Nope :( it's a silent killer, other mods that load data are also likely being affected but none display them as visually as trinkets, so it's hard to tell.
If you want to try and figure out what's causing it, you can perform a binary search, where you disable half of your mods, and see if the issue persists, and keep doing this until you narrow it down to a handful of mods. I'm really sorry there's nothing I can do to resolve this.

**Comment by TheSergioEduP** [comment]
Hi, I was having the same issue and after a lot of turning mods off and on what worked for me was removing "Quilted Fabric API" and installing the regular "Fabric API". I am not sure if it is a bug or some intentional change but it also affects other mods, "Repurposed Structures" in particular was also trowing errors on the console about not being able to load some files.

**Comment by NotGyro** [comment]
I have just reproduced this issue without any additional mods. Currently, I only have `trinkets-3.3.1.jar` and `qsl-1.1.0-beta.19_qfapi-1.0.0-beta.22_fapi-0.56.0_mc-1.18.2.jar` in the mods folder. I'm on Quilt 0.17.0, launching through MultiMc, on `Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111).` There's nothing enlightening present in the logs.

**Comment by NotGyro** [comment]
`Unearthed-fabric-1.18.2-2.3.1.jar` also induces this problem.

**Comment by ryleu** [comment]
strange... i'm using charm with ok zoomer and trinkets in quilt just fine
