### ISSUE TITLE
Can't load or create a world

### ISSUE THREAD

**Issue by RandomScriptKiddie** [emilyploszaj/trinkets#188]
Whenever I have this mod enabled, and I try to join or create a world, it gets frozen on the loading screen forever. This and the Fabric API are the only things I have in my mod folder. Im running minecraft 1.16.5 and am using the 1.16.5 file for Trinkets.

**Comment by emilyploszaj** [comment]
1.16 isn't officially supported, but do you have any relevant logs? Maybe I can figure out a fix
