### ISSUE TITLE
[Suggestion] Banner Capes

### ISSUE THREAD

**Issue by supersaiyansubtlety** [emilyploszaj/trinkets#19]
It would be great if we could wear banners as capes. 
To go along with the [other issue](https://github.com/emilyploszaj/trinkets/issues/13) that requests disabling the cape slot, It would be great if we had a setting that allowed banners but not elytra, so it's purely cosmetic.

**Comment by emilyploszaj** [comment]
I think is more in the scope of its own mod.

**Comment by supersaiyansubtlety** [comment]
Fair enough, guess this is more of a pure API.
