### ISSUE TITLE
[Fabric 1.19] [BUG] Items from Trinkets slots are not counted for death items.

### ISSUE THREAD

**Issue by MrJorman** [emilyploszaj/trinkets#192]
https://github.com/florensie/artifacts-fabric/issues/72 check pls. I use mod Artifacts, Trinkets, and Carpet, Carpet minitweaks.

**Comment by emilyploszaj** [comment]
This is a bug with carpet, not trinkets. There's nothing more I can do from trinkets' end to make carpet realize my items are inventory drops.
