### ISSUE TITLE
Items in trinket slots don't get detected

### ISSUE THREAD

**Issue by Azarilh** [emilyploszaj/trinkets#193]
I have, for example, a mod that checks whether i have a compass in my inventory, if there is, it shows a UI element. The mod does not show the UI element if the compass is in a trinket slot.
Not sure which mod is at fault here, so i tried to use a vanilla bow while having vanilla arrows in a trinket slot, and i couldn't shoot as if i didn't have arrows.

**Comment by emilyploszaj** [comment]
This is a feature that other mods have to add support for, there's nothing Trinkets can do to make them realize there are more items present, because they're only checking in certain places.
