### ISSUE TITLE
compatibility with inventory profiles next

### ISSUE THREAD

**Issue by Jaaaaas** [emilyploszaj/trinkets#196]
Is it possible to make trinkets slots work with profiles from Inventory profiles next mod?
I asked this question on their github and conversation looked like this:
![obraz](https://user-images.githubusercontent.com/109037311/181461392-bb3de43b-00da-487b-9917-66928685aeda.png)
So my question is, are trinkets slots available for manipulation at all time even if not shown and not doing it server side? And if not, would it be difficult to make it work like this?

**Comment by emilyploszaj** [comment]
The Trinkets API exposes the inventories for all of its items at all times, regardless of if a screen is open or not.
