### ISSUE TITLE
Trinkets 

### ISSUE THREAD

**Issue by leaR11** [emilyploszaj/trinkets#211]
hello im having trouble with the texts. I wanted to add slots but the texts looks like this i can't open it with something else than notepad and it looks like this «Zßœvˆu$¾½ëm€‡ØY˜U÷ÙãDÒÚºgn i don't know any of this but idk where everything is beacuse its like that pls help

**Comment by emilyploszaj** [comment]
Seems to be an encoding error, change your encoding editor or download basically any text edtior
