### ISSUE TITLE
trinkets and things causing error 143

### ISSUE THREAD

**Issue by kalethemonster** [emilyploszaj/trinkets#213]
(also posted to things github)
im running a personal vanilla + world and decided to add a few more mods and saw things which i havent used in a while, and after installing, minecraft would not open with things and trinkets installed, and it didnt show the fabric startup error screen. each time i force quit java from activity monitor (im stuck with using a mac atm dont judge) it came up with error 143.

 my mod list (exept for trinkets and things) is additional additions, auth me, axolotl bucket fix(aka axolotol item fix), better biome blend, better tridents, broken nametags, cit resewn, cloth config, detail armor bar, dynamic fps, echoes of the past, edit sign, fabric language koltin, fancy spore blosoms, forge config api port(used by the puzzles lib), global datapack, grind enchants, iris, damb dynam lights, litematica, mali lib, map atlas, more axolotl variants, mending tools dont break, meowing, midnight lib, more metal bars, patchouli, pehkui, petowner, pattable, phosphor, plasmo voice, puzzles lib, sodium+sodium extra, this rocks, variant crafting tables, variant barrels, and variant stick and stuff. they are all in their current versions and working as i type this.

**Comment by BlockOG** [comment]
Have you tried with only trinkets and things to see if the same thing happens? (and fabric api of course)

**Comment by kalethemonster** [comment]
ok i tried with just the api and sodium (bc my mac

**Comment by kalethemonster** [comment]
I DIDNT MEAN TO CLOSE THIS

**Comment by kalethemonster** [comment]
> Have you tried with only trinkets and things to see if the same thing happens? (and fabric api of course)

**Comment by kalethemonster** [comment]
> Have you tried with only trinkets and things to see if the same thing happens? (and fabric api of course)

ok i just tried opening the game with trinkets and things, (with the api and sodium(due to needing it to run the game or my mac chuggs like hell) as well as cloth config and patchouli bc dependency) and it did not start up. and once again sowed the error

**Comment by emilyploszaj** [comment]
I need a crash log to do anything with this, "error code 143" doesn't mean anything.
