### ISSUE TITLE
Add a config file for disabling items

### ISSUE THREAD

**Issue by Jakub-Wilk** [emilyploszaj/trinkets#219]
If possible, it would be really neat if there was a config file that allowed to disable items (by item name) from being able to be used. Right now I'm facing an issue where items from the Hephaestus mod are causing crashes when viewed from the third-person view. Of course, this is (probably) not your issue to fix, but it would be nice to be able to just disable `hephaestus:*` from being able to be inserted into a trinkets slot.

**Comment by emilyploszaj** [comment]
Trinkets can be configured using datapacks, it's possible to remove them from the tags that let them be equipped and put it on the server or in your pack to fix this issue temporarily.
