### ISSUE TITLE
item in hotbar slot 1 gets duplicated to other slots.

### ISSUE THREAD

**Issue by netcore10** [emilyploszaj/trinkets#221]

**Comment by emilyploszaj** [comment]
Is there some more info you can provide?

**Comment by netcore10** [comment]
It's requiem, it add's an extra slot 1, and a server get's confused and all chaos happens in the slots. (Because requiem duplicates a slot one for entities you possess at times)

**Comment by netcore10** [comment]
https://github.com/Ladysnake/Requiem/issues/544#issuecomment-1321005910 they tried fixing it but it still persists.

**Comment by netcore10** [comment]
> [Ladysnake/Requiem#544 (comment)](https://github.com/Ladysnake/Requiem/issues/544#issuecomment-1321005910) they tried fixing it but it still persists.

It was a temporary workaround according to comments, but i think it needs a stronger compatability patch

**Comment by TheIllusiveC4** [comment]
Can you try with the latest Trinkets version (3.4.1) and see if the issue persists? I don't know what's causing it exactly, but the latest update did refactor a lot of the slot loading logic so the compatibility issue should be tested again for relevance.

**Comment by netcore10** [comment]
> Can you try with the latest Trinkets version (3.4.1) and see if the issue persists? I don't know what's causing it exactly, but the latest update did refactor a lot of the slot loading logic so the compatibility issue should be tested again for relevance.

I'm on the latest and the issue still persisted.

**Comment by netcore10** [comment]
there's a decent explanation on requiems issue. https://github.com/Ladysnake/Requiem/issues/544#issuecomment-1203328464

**Comment by TheIllusiveC4** [comment]
Can you provide details about how to reproduce this issue? There should be enough information to allow us to replicate the bug on our end. For instance, you mentioned something about entity possession being part of the cause so listing out the steps to get to that point would be helpful.

**Comment by netcore10** [comment]
Requiem and Trinket's API installed. 
> become a demon (Origins can make it easier to become a demon, so i'd recommend adding that for ease)
>  Die, (sometimes you don't have to die) 
> Posess a zombie or skeleton (Can also splash weakness and eat golden apple while possessing a skeleton to get player body back , 
> Put item in hotbar slot 1, check trinket slots. Any item should practically be duplicated

**Comment by TheIllusiveC4** [comment]
Thanks for the detailed steps. Unfortunately, I don't see that behavior on my end even after following those steps. With an item in the first hotbar slot, nothing gets duplicated or desynced into the Trinket slots after death/possession. Can you provide which Trinket mods/slots you have loaded exactly? Does this happen in single player, multiplayer on a dedicated server, or both?

**Comment by netcore10** [comment]
oh, it's when you place something new into slot 1, it repeatedly get's duplicated. And at the moment, just trinket api, map atlases and other mods that don't matter in this case.

**Comment by netcore10** [comment]
Are you still struggling to replicate this? It can get pretty dangerous to be able to duplicate shulker boxes. I'm not sure what more information i can provide.

**Comment by TheIllusiveC4** [comment]
Yes, I'm still unable to reproduce this even when placing something new into the slot as you described. I've tried many variations of this action with no improper results.

> It could also be server side.

Can you clarify this point? Is this happening in single player, multiplayer on a dedicated server, or both?

> And at the moment, just trinket api, map atlases and other mods that don't matter in this case.

Does it happen if you have ONLY Trinkets API, Map Atlases, and Requiem installed?

**Comment by netcore10** [comment]
> Can you clarify this point? Is this happening in single player, multiplayer on a dedicated server, or both?
 Both single player and multiplayer.
> Does it happen if you have ONLY Trinkets API, Map Atlases, and Requiem installed?
Yes it does. It makes me just as confused to be honest.

**Comment by netcore10** [comment]
Are you sure it's not what requiem has stated when they tried a quick fix?
(it still ended up persisting)

>Requiem adds a dedicated mainhand slot, for smaller mob inventories (eg foxes). Under normal circumstances (depending on mod loading order), this slot is added after Trinkets'. However, when you die, Trinkets refreshes its slots clientside, removing all the existing ones and adding them back while disregarding that requiem's mainhand slot exists. So on the client, the latter slot is before the former while on the server it's the opposite. So when you try to interact with the first Trinkets slot, the server thinks you are actually interacting with Requiem's mainhand slot, and mayhem ensues.

**Comment by TheIllusiveC4** [comment]
> Are you sure it's not what requiem has stated when they tried a quick fix?

The purpose of my questions isn't to determine whether their conclusion is correct or not. I'm trying to gather enough information to reproduce the issue because we cannot fix it if we cannot 1) reproduce it to observe the behavior and then 2) confirm that any solution we implement actually fixes it.

> Yes it does. It makes me just as confused to be honest.

One last follow-up: Can you list out your versions of Quilt Loader, Quilt API, Requiem, Trinkets API, and Map Atlases? I'll need to try and replicate all your versions exactly as they are.

**Comment by netcore10** [comment]
Quilt FAPI 4.0.0 Beta 19
Requiem 2.0.0- beta 15
Trinkets - 3.4.1
mapatlas - 2.3.0

**Comment by netcore10** [comment]
After some investigating, it happens predominantly on multiplayer. Seems my testing i may have left something in the slots in single player and misinterprited it as being the bug. On my hosted server, and local server, it's much more destructive.
