### ISSUE TITLE
Mod Conflict with SewingMachine

### ISSUE THREAD

**Issue by GStefanowich** [emilyploszaj/trinkets#23]
A user of my mod, [Sewing Machine Utilities](https://www.curseforge.com/minecraft/mc-mods/sewing-machine-utilities) has brought it to my attentions that there is [a conflict between our mods](https://github.com/GStefanowich/MC-Server-Protection/issues/15).

The conflict resides
- [Here (SewingMachine)](https://github.com/GStefanowich/MC-Server-Protection/blob/ebe2c5cfb7e8adaac872a3b45c3fa4838ede745e/src/main/java/net/TheElm/project/mixins/World/Clumps.java#L88-L108)
- [Here (Trinkets)](https://github.com/emilyploszaj/trinkets/blob/7ac1419f774970c77933eef186d18182a93596db/src/main/java/dev/emi/trinkets/mixin/ExperienceOrbEntityMixin.java#L37-L77)

**Comment by emilyploszaj** [comment]
This will also be a conflict with [Smarter Mending](https://www.curseforge.com/minecraft/mc-mods/smarter-mending/) as I've had to fix it before. What I'm willing to do is disable this mixin if your mod is loaded assuming you'll check for trinkets on load and apply a mixin that applies mending effects to trinkets slots in addition to the effect you currently have. Sound good?

**Comment by GStefanowich** [comment]
It appears that in `1.16` of Minecraft that Mojang updated [Mending](https://minecraft.gamepedia.com/Mending), to cover the functionality that my mod added, using a `Predicate` to only retrieve damaged armor items.

> Mending now repairs only items that are damaged instead of picking items at random.

As long as your mod also does the same, you can remove the check for my mod, as I no longer need the Mixin.

Thanks,
