### ISSUE TITLE
[1.19.3] Cosmetic Armor Trinkets Addon is broken on Trinkets Polymer fork.

### ISSUE THREAD

**Issue by masterblaster221** [emilyploszaj/trinkets#230]
All there is to it is the Armor's not Visible. I'm using Polymc to run Cosmetic Armor mod on my server. BTW, a cool mod you made here and I Really don't care if it's patched but reporting helps developer's so ya.

**Comment by masterblaster221** [comment]
wrong github sorry

**Comment by Patbox** [comment]
This is caused by how polymer port / visual armor works. It's not issue with Trinkets

**Comment by masterblaster221** [comment]
wierd
