### ISSUE TITLE
1.16.5 Trinket Slot for Necklace and Cape glitch functionality, and cape moves to necklace slot after taking damage.

### ISSUE THREAD

**Issue by JosuOh** [emilyploszaj/trinkets#232]
Here is a clip of the bug: https://medal.tv/games/minecraft/clips/R0TvOPR000LsM/d1337KxhRqkM?invite=cr-MSxnQmcsMTIwNTg4Njks
It was working fine before, then I updated the mod to a later version of 1.16.5 and it has begun to bug.

Bug description: Items placed in the cape/wing and necklace slots do not go in correctly, create ghost items, and swap places after taking damage.

Example: If you place the Elytra in the cape slot, it will disappear and be thrown when exiting inventory. Same goes for the necklace.
However, if placed in the opposite slot (i.e. elytra in necklace slot), it will place itself in the correct spot. Doing so will create a ghost copy, and is possible to duplicate using an item of the opposing slot by overwriting said item. 
If right-clicked with item in hand, it will enter the proper slot, but will swap to the opposing slot after taking damage.

Versions that may be related: 
- Curios 0.0.13-1.16.5,
- things 0.1.1
- trinkets 2.6.7
- fabric api 0.31.0+1.16 and 0.34.1+1.16 (I don't know if having these two affect the game)
- curiousshulkerboxes fabric 1.1.1-1.16.5
- artifacts 3.2.0 fabric

**Comment by emilyploszaj** [comment]
Sorry 1.16 is not a supported version
