### ISSUE TITLE
Fabric 1.19.4 No trinket slots

### ISSUE THREAD

**Issue by lospejos** [emilyploszaj/trinkets#239]
Starting brand new generated world and having these mods:

`fabric-api-0.76.0+1.19.4`
`modmenu-6.1.0-rc.4`
`trinkets-3.6.0`

After entering the world, there is no trinket slots. Am I something misconfigured?

Log file has record that `Trinkets` mod was loaded, also this mod is present in modmenu:
![image](https://user-images.githubusercontent.com/4608475/227031843-c2a4b00b-35ee-413f-86eb-144e875a09c4.png)

Log file has no errors.

Screenshot that shows there is no trinkets:
![image](https://user-images.githubusercontent.com/4608475/227031265-31b5167e-c703-4237-af54-e3077df52c19.png)

Please assist. Thanks.

**Comment by TheIllusiveC4** [comment]
If there are no mods that use Trinkets, no slots will appear because no mods have added them. Trinkets does not add any by itself.

**Comment by emilyploszaj** [comment]
What C4 said is correct.
