### ISSUE TITLE
Tooltip issues

### ISSUE THREAD

**Issue by Focamacho** [emilyploszaj/trinkets#24]
Hello! I'm having some issues with Trinkets Tooltips. (1.16)

Here is a screenshot of my issue:
![image](https://user-images.githubusercontent.com/48870573/85478523-c6992780-b592-11ea-81ee-8a5947e661fa.png)

It seems that some texts are not being translated correctly, including attributes.

**Comment by emilyploszaj** [comment]
this was fixed in 2.6.0, I'm not sure about the attributes I'm pretty sure that's not my fault
