### ISSUE TITLE
Possible compatibility issue 

### ISSUE THREAD

**Issue by NetunooOG** [emilyploszaj/trinkets#241]
Cant equip elytra at all, in chest or cape slot. Just full crashes and cant reload into the world. I do have a very large mod pack but this is the only mod that has any effect on how its equipped, of course with elytra slot mod. Have tried uninstalling the slot mod still crashes. Also had the elytra physics mod and tried it with out that as well with no change.
Error "Float float float" void 1 for all runs sometimes I get the random tick wont load error 1 but mostly the first one. Very easy to replicate. Just Load any world new or old and try to equip an elytra. Not sure about modded elytras but im assuming it will just crash, ill test after this post.
Plz help, thx!!!

**Comment by emilyploszaj** [comment]
Trinkets does nothing with elytra, I don't believe it could have anything to do with your issue.

**Comment by NetunooOG** [comment]
Im so confused then, thx for fast reply
