### ISSUE TITLE
Trinket causing crashing on 1.19.4 Fabric

### ISSUE THREAD

**Issue by Sourpunch14** [emilyploszaj/trinkets#243]
https://pastebin.com/ftCHKC8R My log

Removing the mod that is dependent on Trinket still causes the crashing on startup. It's Trinket itself causing the crashing. Both on version 3.4.2 and on 3.6.0. (The former is what the mod recommended)

**Comment by TheIllusiveC4** [comment]
> It's Trinket itself causing the crashing.

If it is Trinkets itself causing the crash, then you will need to share a crash log with _only_ Trinkets and Fabric API installed. Otherwise, it would likely be another mod causing the issue.
