### ISSUE TITLE
class file for dev.onyxstudios.cca.api.v3.component.ComponentV3 not found

### ISSUE THREAD

**Issue by TheLOL003** [emilyploszaj/trinkets#244]
I am trying to use the getEquipped() method but I am getting an error: `class file for dev.onyxstudios.cca.api.v3.component.ComponentV3 not found`

This is my code:
```java
public List<ItemStack> getTrinkets(LivingEntity p) {
    Optional<TrinketComponent> trinket = TrinketsApi.getTrinketComponent(p);
    if (trinket.isEmpty()) {
        return null;
    }
    return trinket.get().getEquipped(it-> true).stream().map(pair -> pair.getRight()).toList();
}
```
How can I fix this?

**Comment by emilyploszaj** [comment]
Do you have any more info? Are you sure you're depending on the correct version of the mod for your version of minecraft?

**Comment by emilyploszaj** [comment]
What does your build gradle look like?

**Comment by NeRdTheNed** [comment]
I had the same problem when upgrading to Loom 1.1 (Loom 1.0 doesn't have this issue). You can add ``modImplementation "dev.emi:trinkets:5.1.0"`` to manually fix it.

**Comment by gliscowo** [comment]
This issue is caused by the fact that Trinkets depends on CCA with the `modImplementation` config - this should be `modApi` since CCA classes are exposed as part of Trinket's public API. It has not manifested previously because Loom <1.0 did not properly implement this distinction for dependencies.

**Comment by mshailz** [comment]
> I had the same problem when upgrading to Loom 1.1 (Loom 1.0 doesn't have this issue). You can add `modImplementation "dev.emi:trinkets:5.1.0"` to manually fix it.

Did you replace or add the mod implementation? I'm also getting the error of .isEquipped(). Like OP, I'm on 1.19.4, Trinkets 3.6.0, and loom 1.2.

**Comment by KxmischesDomi** [comment]
Had the same issue. Thanks to y'all with the help here <3
