### ISSUE TITLE
[1.19.2] Latest ver. Items equipped on trinket slot obscure the view when using First Person Model mod

### ISSUE THREAD

**Issue by KonstaVilkman** [emilyploszaj/trinkets#245]
![image](https://user-images.githubusercontent.com/73310940/230926062-3d943fcf-096d-4a09-a793-8cfe9bcda2a8.png)
![image](https://user-images.githubusercontent.com/73310940/230926098-c3baada6-343f-4d4f-be1a-41a981124153.png)
![image](https://user-images.githubusercontent.com/73310940/230926161-0ad1ab82-2339-4375-a122-1c1a04995921.png)
![image](https://user-images.githubusercontent.com/73310940/230926186-aef28b8a-5699-468a-9a04-347a1e52ddec.png)

**Comment by emilyploszaj** [comment]
This seems like an issue with the first person model mod, there's really no reasonable generic solution Trinkets could do to solve this.

**Comment by AlienXtream** [comment]
FPM's dev cant really fix this either ( https://github.com/tr7zw/FirstPersonModel/issues/362 )
really, all us users need is either a config or per slot toggle option to hide rendering certain trinkets. i'd be happy with a global setting to "disable trinket rendering".
