### ISSUE TITLE
slot_id changes do not apply on world load

### ISSUE THREAD

**Issue by Andrew6rant** [emilyploszaj/trinkets#247]
I am changing the `slot_id`'s of Trinket's default slots, but the changes only apply after `/reload` is ran.

Here are the affected files:

```
data\trinkets\slots\head\group.json
data\trinkets\slots\chest\group.json
data\trinkets\slots\legs\group.json
data\trinkets\slots\feet\group.json
data\trinkets\slots\offhand\group.json
```

The ID's I changed:

head - 5 -> 78
chest - 6 -> 79
legs - 7 -> 80
feet - 8 -> 81
offhand - 45 -> 77

Before `/reload` is ran (slots do not work):

![before_reload](https://user-images.githubusercontent.com/57331134/232156055-1b1cc830-f2cc-46e7-b988-468409e0d495.gif)

After `/reload` is ran (slots work):

![after_reload](https://user-images.githubusercontent.com/57331134/232156069-d1c74672-fec6-4db4-b049-314340d56734.gif)

`/reload` has to be ran every time the player enters the world.

**Comment by emilyploszaj** [comment]
This seems like some very peculiar data loading issue, Trinkets has no special casing for slot ids and everything is read from json, so I'm not sure what could be requiring a reload, have you tested different ways of providing these files like with a mod datapack/world datapack/editing trinkets?

**Comment by Andrew6rant** [comment]
My initial test was through a mod-datapack (you can see the commit here: https://github.com/Andrew6rant/BigInv/commit/fa8988a0c4d2d600462c15464fdee4930be89784). I then tested with a regular world datapack, and I had the exact same issue. Editing the Trinkets mod itself also led to the same problem.

But, now I think I know what is happening (and it is my fault, whoops!). It's most likely related to the way BigInv replaces slots. Specifically, armor and offhand ones.

At first I thought it was happening for slots outside of Vanilla's default range (45+), but then found out that this only breaks with `EquipmentSlots`. If I make a mod datapack/world datapack or edit the mod to change the `slot_id`s to be: 78, 79, 35, 12, then 35 and 12 will show up fine but 78 and 79 will need a `/reload` to appear.

**Comment by emilyploszaj** [comment]
Oh that's very peculiar, but I believe outside of the scope of Trinkets, so I'll be closing. Best of luck with screen handlers, they are prickly
