### ISSUE TITLE
Applied tablets don't charge when worn into trnikets slots

### ISSUE THREAD

**Issue by SireTeddy** [emilyploszaj/trinkets#249]
Hello, i'm here because i play on Sky of FABRIC ation 3 and i have a problem with AE2 tablets (and other items needed to be charged), in effect, when i want put my item on trinket slots, it doesn't charge 
could you fix it ?
i play on the version :  3.3.1 on 1.18.2 mc version

**Comment by emilyploszaj** [comment]
This means mods are simply interfacing with Trinkets wrong and forgetting to charge in the slot, there's nothing I could do.
