### ISSUE TITLE
Allow disabling the "Equippable in" tooltip text

### ISSUE THREAD

**Issue by NyakoFox** [emilyploszaj/trinkets#251]
Someone opened an issue asking for this in my repo (https://github.com/NyakoFox/VanitySlots/issues/12). My mod makes all armor equippable in new trinket slots, so the text can make the tooltips become quite cluttered. An option to disable the text would be nice (maybe a per-slot thing? dunno)

**Comment by emilyploszaj** [comment]
This is actually already supported on a per-slot basis via `tooltip_predicates` which can be found here https://github.com/emilyploszaj/trinkets/wiki/Trinkets-Data-Formats
