### ISSUE TITLE
[1.16.5] Cannot Load into a World with Trinkets mod Enabled

### ISSUE THREAD

**Issue by runnerman15** [emilyploszaj/trinkets#255]
I am trying to use the trinkets mod on 1.16.5 using Fabric version 0.14.1 on Windows 11. The Trinkets version I am using is 2.6.7. Whenever I try to load into a world or create a world, the game will sit on the loading screen forever. When I try to load into a world, it will sit at 100%. When I create a new world, it will sit at 4%. I have tried using the newest version of Fabric (0.14.21), but it does the same thing. I've tried disabling Atlas and the game will load into a world. I've also tried disabling every mod but trinkets, modmenu, and Fabric API and the game will crash immediately after creating a new world. I've attached the crash report.  I've tried just using tickets by itself with fabric API and the game will freeze on the world loading screen. I'm thinking it might be a compatibility issue with the other mods I am using. Here is a list of mods I have installed: Cinderscapes 1.4.0, Cloth Config 4.16.91, Fabric API 0.42.0, Iris Mod 1.4.5, Atlas Mod 1.2.5, Mod Menu 1.16.23, Sodium 0.2.0 Build 4 and, Traverse 3.3.3. Thanks in advance!
[crash-2023-06-16_15.37.49-server.txt](https://github.com/emilyploszaj/trinkets/files/11776715/crash-2023-06-16_15.37.49-server.txt)

**Comment by fzzyhmstrs** [comment]
Cardinal Components, which is embedded into Trinkets, is having an issue with the Fabric API. I would try manually installing a newer version of CCA (2.8.3) alongside Trinkets to see if that helps.

**Comment by runnerman15** [comment]
> Cardinal Components, which is embedded into Trinkets, is having an issue with the Fabric API. I would try manually installing a newer version of CCA (2.8.3) alongside Trinkets to see if that helps.

Ok Ill try this later tonight thank you!

**Comment by runnerman15** [comment]
> Cardinal Components, which is embedded into Trinkets, is having an issue with the Fabric API. I would try manually installing a newer version of CCA (2.8.3) alongside Trinkets to see if that helps.

It worked thank you!
