### ISSUE TITLE
[CRASH/BUG] Crash when taking an item out of the legs trinket area [Fabric 1.19.2/0.14.21]

### ISSUE THREAD

**Issue by pokesmells** [emilyploszaj/trinkets#257]
**`Steps to reproduce:`**

**1. Place a trinket inside of the legs trinket slot whilst in creative.**

**2. Try taking the item out of said slot**

**3. Crash when action is completed**

Crash log - https://mclo.gs/3uwiZyP
Latest log - https://mclo.gs/Ey3HMVi

Minecraft version - 1.19.2
Fabric Loader - 0.14.21
Os Version - Windows 11

**Comment by emilyploszaj** [comment]
This seems to be related to legendary tooltips and not trinkets.
