### ISSUE TITLE
Mending XP does not properly apply to held items while using items in chest slot

### ISSUE THREAD

**Issue by Processhf** [emilyploszaj/trinkets#26]
This is pretty confusing to explain but essentially on our server if we have an item in either our cape slot or chestplate slot, xp does not go to our held items with mending.The XP bar will just fill without repairing the item held in hand. Items equipped on the player still gain XP through mending properly. Removing the chestplate AND cape is the only way to direct XP to the held item.

**Comment by Processhf** [comment]
I'd like to update this by saying XP is intermittently not going to the chestplate slot, but is reaching the cape/elytra slot. We had to install a server that allows you to apply XP to mending items manually as a workaround.

**Comment by emilyploszaj** [comment]
I think this has to do an older mixin using some old code for how mending was applied, I'll give it a crack

**Comment by emilyploszaj** [comment]
This has been fixed in 2.6.2.
