### ISSUE TITLE
Cannot access dev.onyxstudios.cca.api.v3.component.ComponentV3 (component.isEquipped)

### ISSUE THREAD

**Issue by JSJBDEV** [emilyploszaj/trinkets#262]
![image](https://github.com/emilyploszaj/trinkets/assets/16166991/801f124d-46e8-441a-8e56-57a63fb6691a)
whilst updating to 1.20, I get this error for isEquipped.

my build.gradle is constructed as suggested on the front page of this mod using `modImplementation "dev.emi:trinkets:3.7.0"` and the repositories set.

The rest of the methods used seem to work fine - I saw a closed issue regarding this not being found, but this seems to be different, however, should I also have CCA api in my mod dependencies?

**Comment by Ultimushadow** [comment]
You might want to take a look at this issue: https://github.com/emilyploszaj/trinkets/issues/264
It's been a bit since the CCA repo has changed, I'm sure you've found a solution or moved on to other things but if others get the same error I think it would be helpful to guide them to the other issue

**Comment by MJRamon** [comment]
@emilyploszaj @Ultimushadow 
Did update build.gradle and new Ladysnake repository, but still getting `Cannot access dev.onyxstudios.cca.api.v3.component.ComponentV3` error in
```
///
List<Pair<SlotReference, ItemStack>> list = trinkets.getEquipped(TrinketItems.AMULET);
///
```

Gradle: 8.1
fabric-loom: 1.2-SNAPSHOT

minecraft_version=1.19.2
yarn_mappings=1.19.2+build.28
loader_version=0.14.21
fabric_version=0.76.0+1.19.2

trinkets_version=3.4.1


I cannot update to a newer Minecraft version, even in future. What can be done?

**Comment by Ultimushadow** [comment]
Did you try importing ComponentV3?

**Comment by MJRamon** [comment]
> Did you try importing ComponentV3?

I am sorry, I am not that in-depth with gradle, learning how to code by myself, how exactly should I import it?

**Comment by emilyploszaj** [comment]
Sorry for the delay everyone, Trinkets 3.7.1 has been released which targets the newest CCA maven, and transitively includes the dependency for newer versions of Loom. This issue should be resolved if updated.
