### ISSUE TITLE
[Feature] Not yet working with 1.20.1

### ISSUE THREAD

**Issue by Seegras** [emilyploszaj/trinkets#263]
Some other mods depend on it. please recompile, thank you.

**Comment by emilyploszaj** [comment]
Can you provide any log or information I can use to debug this issue?

**Comment by Tursiops-G** [comment]
Seems to work fine for me on 1.20.1 (with both Fabric and Quilt modloaders).
Do you have at least 1 Trinkets-API capable mod loaded (Ex: Charm of Undying, etc.)?
Otherwise, there will be No accessible trinket slots shown at all...

**Comment by emilyploszaj** [comment]
Oh, yeah I updated the version number on Modrinth and forgot to close this.
