### ISSUE TITLE
Cardinal Components API has moved

### ISSUE THREAD

**Issue by Ultimushadow** [emilyploszaj/trinkets#264]
Hello, I was trying to implement a trinkets item into another mod and could not for the life of me get the gradle to work, after some immense headaches I realized that the CCA has _been removed from jfrog entirely_, so the example dependency for mod developers you have on your readme is no longer going to work!

https://github.com/OnyxStudios/Cardinal-Components-API
From their GitHub, the new repository location: 

repositories {
    maven {
        name = 'Ladysnake Mods'
        url = 'https://maven.ladysnake.org/releases'
    }
}

**Comment by emilyploszaj** [comment]
Thanks for letting me know, I've changed the recommendation in the README and will update the repository in the gradle the next time I publish a release.
