### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Rogenar** [emilyploszaj/trinkets#266]
Trinkets slots are not opening. It's incompatible with the Inventorio mod. Can you bring a new update that will fix this issue?
versiyon; trinkets-3.7.0 fabric
versiyon; [1.20+] Inventorio 1.9.2 fabric
![254924488-02116c31-1ce3-4f31-8996-1c253f7b2f9d](https://github.com/emilyploszaj/trinkets/assets/122460325/4a23f9e8-adb0-40d5-92be-bc890b4c0f4a)

**Comment by emilyploszaj** [comment]
This is outside of trinkets' purview

**Comment by Rogenar** [comment]
So this problem will not be fixed?

**Comment by emilyploszaj** [comment]
This is not something trinkets can reasonably fix, it's the responsibility of inventorio
