### ISSUE TITLE
inventorio and trinkets mismatch

### ISSUE THREAD

**Issue by Rogenar** [emilyploszaj/trinkets#267]
Inventorio mod maker says that there is a button in the upper right corner of the inventory in your mod and that we can access the trinkets slots by switching to the vanilla inventory with this button, but I did not see such a button.

**Comment by SiverDX** [comment]
uuh

you mean the button in the top right from the screenshot (in the description) here
https://www.curseforge.com/minecraft/mc-mods/inventorio

that'd be a button from the mod inventorio

**Comment by Rogenar** [comment]
yes and that button is not visible

**Comment by SiverDX** [comment]
shouldnt you ask inventorio about that?

**Comment by Rogenar** [comment]
I asked her too but did not get a clear answer.
