### ISSUE TITLE
Crash on armor equip

### ISSUE THREAD

**Issue by unrusoanonimo** [emilyploszaj/trinkets#268]
When cartain armors are equiped using Shift+left click, they go to the wrong slot and the game crashes, that also happens when trying to equip the item on the wrong slot

[crash-2023-07-24_14.10.09-server.txt](https://github.com/emilyploszaj/trinkets/files/12147067/crash-2023-07-24_14.10.09-server.txt)
[crash-2023-07-15_14.46.29-server.txt](https://github.com/emilyploszaj/trinkets/files/12147068/crash-2023-07-15_14.46.29-server.txt)

**Comment by emilyploszaj** [comment]
This is a twifor issue, I don't believe it even involves trinket slots.
