### ISSUE TITLE
Bugged asf

### ISSUE THREAD

**Issue by Aabaddon** [emilyploszaj/trinkets#275]
If you equip any trinket, literally any it just duplicates the same trinket and places it in every single slot in the inventory, it is not compatible with "cosmetic armor" a mod ported by its own developer from forge to fabric, it works in forge but in fabric having to rely on "trinkets" its a completely useless mod, the same with "glass armor", its highly unstable too and impossible to use in creative mod

**Comment by emilyploszaj** [comment]
This issue is partially about other mods, and partially references the vanilla creative desyncs which already have other tracking bugs so I'm going to close this one as a duplicate.
