### ISSUE TITLE
[Feature Request] Hide option like curios

### ISSUE THREAD

**Issue by suuty** [emilyploszaj/trinkets#277]
the ability to hide trinkets like in the curios mod would be very nice

**Comment by Donokami** [comment]
It would be also interesting to show the Trinkets slots only if one of the items compatibles were in the inventory!

**Comment by emilyploszaj** [comment]
#157

**Comment by b2ptvc5kf9-ui** [comment]
not planned? man god forbid people want this mod to have similar features to the mod its trying to compete with
