### ISSUE TITLE
Missing dependencies in pom

### ISSUE THREAD

**Issue by gniftygnome** [emilyploszaj/trinkets#278]
It seems like the latest version is missing dependencies in its pom, which causes recent Loom versions to fail to provide them in dev environments (quite annoyingly).

I just had the same issue in Biolith after upgrading to Loom 1.3.  It appears it is now necessary to follow this change in the fabric example mod in order for the pom's dependency section to generate correctly:

https://github.com/FabricMC/fabric-example-mod/commit/8adede095a379f0f18984d1ec2b4a46a4b5d29a7

**Comment by emilyploszaj** [comment]
This should be resolved in 3.7.2 and 3.8.1
