### ISSUE TITLE
[feature request] option to keep trinkets on death

### ISSUE THREAD

**Issue by n0proxy** [emilyploszaj/trinkets#279]
Really wish I had more control over exactly which items drop on death when keepInv is on (ie hotbar, equipped armor, inv) and part of that would be really nice if I could have just my equipped Trinkets items stay with me on death.

**Comment by emilyploszaj** [comment]
Trinket slots can have drop rules that function this way, they can be configured on a slot by slot basis using datapacks. The format is documented here https://github.com/emilyploszaj/trinkets/wiki/Trinkets-Data-Formats
