### ISSUE TITLE
Reverse-search Trinket slot uses

### ISSUE THREAD

**Issue by twenty41** [emilyploszaj/trinkets#282]
The ring slot is enabled in my pack and I can't figure out why. I have no rings, searched with JEI

Surely if Trinkets is being triggered by the presence of a valid item, there must be a way to read what that valid item is.

How can I do this?

**Comment by emilyploszaj** [comment]
Trinkets slots are enabled by mods explicitly in their datapacks. Look for the `trinkets` folder, you can also check the contents of the `trinkets:ring` tag
