### ISSUE TITLE
Slots enabled but hidden from inventory

### ISSUE THREAD

**Issue by denerka** [emilyploszaj/trinkets#284]
Hi there, I'm looking to fully control a trinket slot through commands, therefore I need the slot enabled but hidden from the inventory screen for all players.

I found issue https://github.com/emilyploszaj/trinkets/issues/70 that suggests this might be possible, but haven't been able to find more information. Just wondering if you could expand on this a bit if you get a chance. Thank you!

**Comment by emilyploszaj** [comment]
Trinkets can have modifiers that adjust the amount of slots of different types exist, unfortunately these can only be applied by other trinkets, so I don't believe they suit your case of needing to be done through commands.
