### ISSUE TITLE
[Bug] Trinkets slot is only shown in creative mode

### ISSUE THREAD

**Issue by th3heindnsiw** [emilyploszaj/trinkets#285]
In survival mode, when I hover my cursor in chest slot, the slot did not show. But it only shows when I'm in creative mode.
![Screen Shot 2023-11-30 at 22 00 47](https://github.com/emilyploszaj/trinkets/assets/104712151/467ecc40-3909-47f0-910c-b6d016a888ec)
![Screen Shot 2023-11-30 at 22 01 25](https://github.com/emilyploszaj/trinkets/assets/104712151/5cfb7b72-8b92-45ee-9933-ac31a5cebd77)

Please tell me if this is an actual bug or I'm doing something wrong.

**Comment by emilyploszaj** [comment]
Can you reproduce this in singleplayer with less mods? you seem to have several installed, some of which seem to change the survival inventory

**Comment by GamingAmateur233** [comment]
You're using the Inventorio mod, which mostly changes the survival inventory UI completely. There is a switch in the survival modded UI to disable it (you can configure that with a hotkey with Cloth). There, you can access Trinkets and other modded UI components that are not Inventorio.
