### ISSUE TITLE
[1.20.1 Fabric] Is wearing multiple of the same trinket intended?

### ISSUE THREAD

**Issue by Robotgiggle** [emilyploszaj/trinkets#290]
In the past, you were only able to wear one of any given trinket, even if there were multiple valid slots. However, in the version of the mod I'm using (version 3.7.1 for fabric 1.20.1, to be specific) I'm able to wear multiple of the same type of ring (tested on all Botania rings, including the relics) with one in each ring slot. Is this a new feature, or is it unintended behavior?

**Comment by emilyploszaj** [comment]
You've always been able to wear multiple of the same trinket, if a mod had a restriction on this in the past, it would be handled by them, and not trinkets.
