### ISSUE TITLE
Windows Defender Flagging Trinkets 3.7.2 As A Trojan

### ISSUE THREAD

**Issue by Fyoncle** [emilyploszaj/trinkets#297]
So lately i been trying out a modpack and trinkets are getting flagged as a virus and it deletes from my computer and that causing modpack to not launch and get in need of trinkets because of "Elytra Slot" mod, is this false flag or anything? is this even fixable.

**Comment by SiverDX** [comment]
https://www.curseforge.com/minecraft/mc-mods/collective/files/5177354

has an explanation for this

**Comment by Fyoncle** [comment]
> https://www.curseforge.com/minecraft/mc-mods/collective/files/5177354
> 
> has an explanation for this in the changelog

Explanation not needed, since i already know its false flagging but if i include trinkets in my modpack people cant join the modpack because windows defender immediately deletes trinkets in everyone that downloaded the modpack and that makes the modpack unplayable, is it possible to fix this issue with the mod itself?

**Comment by SiverDX** [comment]
as per explanation which you apparently already understand: no
this is on windows

**Comment by Fyoncle** [comment]
Ah, thank you then..
