### ISSUE TITLE
Disabling the mod's custom tooltip

### ISSUE THREAD

**Issue by maityyy** [emilyploszaj/trinkets#300]
Is it possible to disable this text on 1.20.1?
![image](https://github.com/emilyploszaj/trinkets/assets/47220489/07cc4915-fe14-499a-8e5e-eade81be4cd1)

And yes, thanks for the cool API! :)

**Comment by emilyploszaj** [comment]
https://github.com/emilyploszaj/trinkets/wiki/Trinkets-Data-Formats see the tooltip predicate for slots

**Comment by maityyy** [comment]
It worked, thanks
