### ISSUE TITLE
[Feature Request] Right click to equip trinkets in the first valid slot

### ISSUE THREAD

**Issue by thomasglasser** [emilyploszaj/trinkets#301]
It would be nice for gameplay if right-clicking while holding a trinket puts it in the first valid slot like Curios.

**Comment by TheIllusiveC4** [comment]
This isn't default behavior in Curios, it needs to be specified by the mod in their implementations. Similarly, Trinkets already has a `TrinketItem.equipItem` for calling equip on use behavior.

**Comment by thomasglasser** [comment]
Because that behavior is defined in `TrinketItem`, it must be re-implemented in any item that uses a different base class or multi-loader projects where the item can't extend TrinketItem. Curios putting the method in the interface allows for better configuration.

**Comment by emilyploszaj** [comment]
`TrinketItem.equipItem` is static, you can call it from wherever.
