### ISSUE TITLE
[Suggestion] Make TrinketItem as an interface.

### ISSUE THREAD

**Issue by IAFEnvoy** [emilyploszaj/trinkets#302]
The TrinketItem class only extends the Item class, which makes it difficult to add special things such as weapons into slots.

So i think making it to an interface like Curios API is better.

**Comment by fzzyhmstrs** [comment]
`Trinket` is an Interface, which `TrinketItem` implements.

**Comment by emilyploszaj** [comment]
fzzy is correct, the interface you're looking for is `Trinket`. `TrinketItem` is just a class that extends item and implements `Trinket` with auto registration, for convenience sake.
