### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Mukkod** [emilyploszaj/trinkets#303]
Game crashes on launch.

org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getActualReachDistance(DLnet/minecraft/world/level/Level;Lnet/minecraft/world/entity/player/Player;)D in mixins.reach-entity-attributes.json:ItemMixin from mod reach_entity_attributes failed injection check, (0/4) succeeded. Scanned 1 target(s). Using refmap refmap.reach-entity-attributes.json

this is the specific error which only shows on the console. I *AM* using Sinytra Connector so if that is the issue, please let me know.

**Comment by emilyploszaj** [comment]
This isn't a trinkets crash, it's reach entity attributes.

**Comment by Mukkod** [comment]
its specifically when trinkets is installed. without trinkets, the game loads up fine and then screams at me because Spectrum doesnt have Trinkets. with trinkets, it gives that error and crashes on bootstrap while trying to load.
    On Tuesday, April 2, 2024 at 10:09:08 PM EDT, Emily Rose Ploszaj ***@***.***> wrote:  
 
 


This isn't a trinkets crash, it's reach entity attributes.

**Comment by Mukkod** [comment]
Like i said in my original post, i am using Sinytra Connector. i think theres a clash between Trinkets and Curios just based on the fact that they do the same thing. i just need confirmation on if that is the case or not so i can re-evaluate my plans with my pack.

**Comment by TheIllusiveC4** [comment]
Trinkets and Curios have separate systems so they wouldn't clash on just the basis that they do the same thing. The error that you've shared is specifically from Reach Entity Attributes crashing. You should remove Reach Entity Attributes, or whichever mod is embedding it, and then re-test for confirmation.

**Comment by emilyploszaj** [comment]
Either way, this is a reach entity attributes crash and even if it was in trinkets, I can't provide support to sinytra connector
