### ISSUE TITLE
Crash with JEI's cheat mode when the player has 8 or more trinket slots

### ISSUE THREAD

**Issue by ochotonida** [emilyploszaj/trinkets#306]
- Minecraft 1.20.1
- Fabric API 0.92.1+1.20.1
- Trinkets 3.7.2
- JEI 15.3.0.4

If the player has any 8 trinket slots, and attempts to cheat in an item from JEI while in the creative mode survival inventory, the game crashes. See https://github.com/ochotonida/artifacts/issues/250 or any of the issues linked there for more information.

Crash report with just JEI, Trinkets, and a data pack:
[crash-2024-04-13_12.03.55-client.txt](https://github.com/emilyploszaj/trinkets/files/14967021/crash-2024-04-13_12.03.55-client.txt)

**Comment by emilyploszaj** [comment]
This is likely related to trinkets adding more slots to the survival inventory, but the crash is on JEI's end.

**Comment by mezz** [comment]
hi @emilyploszaj 
I call `net.minecraft.world.inventory.AbstractContainerMenu#broadcastChanges` which triggers the crash.
I am not doing any kind of specific slot math here, just calling a vanilla method to update the player's carried item.
Can you help me understand how this crash is happening?

**Comment by emilyploszaj** [comment]
Is this happening off render thread or similar? Trinkets can modify the amount of slots a player has in an inventory pretty freely and I could imagine threading causing an issue if slots were to be removed, other than that, I can't figure why this issue would occur.

**Comment by mezz** [comment]
hm good call, let me make sure my fabric packet handling is queuing work onto the render thread correctly

**Comment by mezz** [comment]
Hmm the stack trace shows 
`Thread: Render thread`

**Comment by mezz** [comment]
This issue has been resolved in JEI:
* https://github.com/mezz/JustEnoughItems/issues/3460
