### ISSUE TITLE
Update to 1.20.5

### ISSUE THREAD

**Issue by NyakoFox** [emilyploszaj/trinkets#307]
I'm not opening this as a "please do this urgently" type of thing, instead just as a way to mark it's not compatible yet.

**Comment by vico93** [comment]
I second this! Also i take the opportunity to inform that 1.20.6 almost 100% compatible with 1.20.5 mods, since the only change for now is fixing [MC-271109](https://bugs.mojang.com/browse/MC-271109)

**Comment by Ioandar** [comment]
yes please! 
I have a mod on rollout testing for fabric 1.20.5 and would love to include my trinkets anklet :D

**Comment by rakantoh** [comment]
+1 to update, thanks
