### ISSUE TITLE
Any way to configure the amount of slots?

### ISSUE THREAD

**Issue by Etherrrr** [emilyploszaj/trinkets#31]
Is there any way to add slots like which makes it possible to wear more than one ring on single hand?

A configuration file may be good...
Thanks a lot

**Comment by emilyploszaj** [comment]
it is possible to make slots that behave like other slots, such as a ``hand:ring2`` that checks items against the identifier ``hand:ring`` but that could possibly lead to issues with mods that check specific slots for their items. A config file for stuff like this is out of scope for trinkets, this is an api mod and slots are defined and added by mods that use it.
