### ISSUE TITLE
Enchantments on items in cape slot don't seem to work.

### ISSUE THREAD

**Issue by cultab** [emilyploszaj/trinkets#311]
I noticed this with Water Protection on a Crystalite Elytra on the cape slot. The effects of the enchantment don't work when the elytra is in the cape slot, works fine in the armor slot.

#308 Mentions a similar issue with another enchantment. 

I have also found that other effects such as getting lift from hydrothermal vents from the Better End mod don't work.

**Comment by emilyploszaj** [comment]
Mods need to implement enchantment checking themselves unfortunately, nothing trinkets can do.
