### ISSUE TITLE
How do I edit an item attribute with commands?

### ISSUE THREAD

**Issue by KingYamiJ** [emilyploszaj/trinkets#315]
I finaly found out. 

*Movement Speed example:
/give @p ItemName{TrinketAttributeModifiers:[{AttributeName:"generic.movement_speed",Name:"generic.movement_speed",Amount:0.1,Operation:1,UUID:[I;-229862875,-1670430074,-1905662442,852229751],Slot:"hand/ring"}]} 1

for anyone who has the same doubt.

**Comment by emilyploszaj** [comment]
Trinkets are acceptable in slots based on data driven predicates, for almost all slots this would be tag based, so you'd want to add items to tags like the wiki describes.
