### ISSUE TITLE
Compaible with Tombstones

### ISSUE THREAD

**Issue by CWimZy** [emilyploszaj/trinkets#318]
When you die, all the items from the trinkets slots fall out, and are not saved in the tombstone like the rest of the items. It's unpleasant when you're dead and some of the things are missing. You may need to contact the developer of the tombstones mod for a solution. I have already written to him in discord.
sorry for my English, I use google translate

**Comment by emilyploszaj** [comment]
Tombstones will need to add native support, trinkets can not.
