### ISSUE TITLE
1.21 release

### ISSUE THREAD

**Issue by NyakoFox** [emilyploszaj/trinkets#321]
I see the 1.21 port has been merged -- is 3.10.0 going to be released soon?

**Comment by ReneMuetti** [comment]
As far as I have seen, the build process has been canceled. This will certainly be the cause. Unfortunately, I can no longer find where I saw this

**Comment by Stein-N** [comment]
When i understand it correctly on Emi's Discord, she is waiting for the neoforge port made by someone else. When the Port is ready she will publish the 1.21 versions

**Comment by BrandonPotter0** [comment]
Fingers crossed for a 1.21 release. Really want to use this with Travellers Backpack on Fabric.

**Comment by Lakuna** [comment]
1.21 support is out on Modrinth.

cc @Legendmanj
