### ISSUE TITLE
ItemStack slot info missing on 1.20.1 fabric

### ISSUE THREAD

**Issue by lexi-the-cute** [emilyploszaj/trinkets#327]
I'm currently looking at https://github.com/Mari023/AE2WirelessTerminalLibrary/issues/242 in which ItemStack instances are changed and the slot the ItemStack was stored in is not known. I'm opening this issue to see if y'all would be able to help with a workaround to this issue

**Comment by emilyploszaj** [comment]
Trinkets has methods for when the stack in a slot changes, I'm not sure what you mean by "missing info", and I'd need more to go off of on how to help resolve this.
