### ISSUE TITLE
Is there a way to remove trinket slots?

### ISSUE THREAD

**Issue by cargl** [emilyploszaj/trinkets#329]
I can't find the question to this anywhere online or in forums, I need to remove a few slots so people can't use Elytra but Malum, Botania, and a few other mods depend on trinkets. Is this an option? I can't find any config allowing me to change it.

**Comment by emilyploszaj** [comment]
You will need to write a datapack to change the amount of slots of each type present, documentation is located on the github wiki.

**Comment by cargl** [comment]
Thanks, I appreciate the help.
