### ISSUE TITLE
(Fabric, Trinket ver. 3.7.2)On Equip Gets Called When Changing Nbt on Items

### ISSUE THREAD

**Issue by Winman7486** [emilyploszaj/trinkets#330]
While making a trinket and testing it it randomly stopped working, I relized after a while it was because of my trinket's onEquip method reseting nbt every time I would set it.
This seems to be because in the living entity mixin it checks if the item stacks are equal but because of an nbt change they are not.

**Comment by emilyploszaj** [comment]
This is intentional, these methods get called when a stack changes outside of its tick method.
