### ISSUE TITLE
Armor items added to trinket slots don't render?

### ISSUE THREAD

**Issue by nothingtown** [emilyploszaj/trinkets#331]
Hi, I'm not sure what could be causing this, but when I add the <tag:items:trinkets:head/hat> tag to items (via CraftTweaker) such as vanilla helmets or any other helmet armor item, they don't render correctly when placed into the helmet slot. I'm not sure if it's intended or if I need to do something else to make them render.

They just don't render at _all._

If its relevant, I added Let's Do: Beach Party's sunglasses (which are a helmet item) to the hat tag to attempt to render them alongside a SimpleHats hat (I added multiple hat slots). I'm also using Transmog to transmog a helmet into the sunglasses, but I tried it on just the sunglasses and the helmet separately...

**Comment by emilyploszaj** [comment]
Trinket rendering is defined in code. There's no default in place for items that render as armor, because this is possibly not the intended behavior (see, create goggles which render in an alternative position)
