### ISSUE TITLE
API out of date?

### ISSUE THREAD

**Issue by heirofhope** [emilyploszaj/trinkets#335]
im currently writing a mod that uses trinkets, and im trying to create a way for a trinket to check if a player kills a mob and then give some effect after. however, when i try to call `isEquipped` or `getEquipped`, like it says on the API page of the wiki, its just missing from the full implementation. im working in 1.19.2 if that makes any significant difference.

**Comment by emilyploszaj** [comment]
These are methods that exist on the `TrinketComponent` type.
