### ISSUE TITLE
Resource Pack Support

### ISSUE THREAD

**Issue by QwertRvg** [emilyploszaj/trinkets#341]
Is there any way to add Resource Pack support to the Inventory UI?
![image](https://github.com/user-attachments/assets/48a46ed4-2628-4022-845e-4d4b12159cd9)

**Comment by fzzyhmstrs** [comment]
`resources/assets/trinkets/textures/gui/`. you can override them in a resource pack at the same location like any other tex.

**Comment by QwertRvg** [comment]
yeah, but the trinket slots are just normal inventory slots right? couldnt the support be automated?
