### ISSUE TITLE
Trinkets Mod DELETES Traveler's Backpack

### ISSUE THREAD

**Issue by romeotheoracle** [emilyploszaj/trinkets#347]
**0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)**

MINECRAFT VERSION:
1.21.1

MODLOADER:
Fabric - 0.16.7

MODS DISCUSSED:
travelersbackpack-fabric-1.21.1-10.1.3.jar
trinkets-3.10.0.jar

**1. Describe the bug**
When you have Trinkets installed AFTER already having any backpack from Traveler's Backpack equipped, the backpack will turn invisible on your back. It will still be accessible via the hotkey.

If you equip another backpack from Traveler's Backpack to the non-trinket slot (added from Trinkets mod), the backpack you had equipped prior to installing Trinkets will be deleted entirely. I lost a lot of my written books this way and have no way to recover them. 😭

**2. Write steps to reproduce the bug**

IN ORDER:

- Install Traveler's Backpack (version: travelersbackpack-fabric-1.21.1-10.1.3.jar)
- Start a New World.
- Equip any type of backpack from Traveler's Backpack.
- Put a separate (but any type of) backpack from Traveler's Backpack in your inventory. You should have one equipped and one in your main Minecraft inventory.
- Save and exit the game.
- Install Trinkets (version: trinkets-3.10.0.jar)
- Relaunch the game & load your created New World.
- Open your main Minecraft inventory (NOT the Traveler's Backpack inventory) and place the unequipped backpack in your non-trinket slot from the Trinkets mod. Alternatively, you can just simply Shift+Right Click the backpack and it will equipped.
- Your previous backpack will be deleted and forever lost.

**3. What is expected behaviour**

The backpack should not be deleted and should still be accessible. It should have automatically unequipped when Trinkets was installed.

**4. Screenshots (If applicable)**
Currently at work so I cannot reproduce screenshots, but I aim to update this with some when I get home.

**Comment by fzzyhmstrs** [comment]
This seems like a bug with Travelers backpack. Trinkets would have no way to access the non-trinket slot to "delete" anything.

**Comment by emilyploszaj** [comment]
Correct, this is not trinkets' responsibility
