### ISSUE TITLE
Show Me Your Skin! Compatible

### ISSUE THREAD

**Issue by IranMine123** [emilyploszaj/trinkets#350]
Hello I just want trinkets have transparency (or be hidden).
[Show Me Your Skin!](https://github.com/enjarai/show-me-your-skin) mod already offer this feature for armors, shield and elytra.
I don't think the developer of mod can do that, as they said:
>Compatibility with "trinket-like" mods like Travelers Backpack is mostly out of scope for this mod, so I most wont be working on this.
(https://github.com/enjarai/show-me-your-skin/issues/52)

thx.

**Comment by emilyploszaj** [comment]
Trinkets doesn't do rendering itself, so it can't add this feature.
