### ISSUE TITLE
Ghost Items in Creative Inventory

### ISSUE THREAD

**Issue by Wtoll** [emilyploszaj/trinkets#8]
If you go into creative mode and place an item in a trinket slot the item isn't actually real. In creative mode, the elytra, for example, can be placed in the cape slot, but you cannot fly with it. Additionally, when you have an item in a trinket slot that was placed there in creative mode, and then you switch to survival mode and try to remove said item, the item will disappear like it was never there.

[Video Example](https://streamable.com/mau9w)

**Comment by emilyploszaj** [comment]
This was a *really* interesting bug to figure out. Apparently the server checks the index of clicked slots when a packet is sent to be less than or equal to a constant 45 only in creative. This behavior doesn't exist for survival. Fixed in latest release.
