### ISSUE TITLE
Mod conflict with bannerelytra (crash during start up)

### ISSUE THREAD

**Issue by Devil2548** [emilyploszaj/trinkets#9]
Crash report: 
[crash-2019-11-18_12.08.29-client.txt](https://github.com/emilyploszaj/trinkets/files/3860017/crash-2019-11-18_12.08.29-client.txt)

Mods:
bannerelytra-1.0.0
fabric-api-0.4.1+build.245-1.14
trinkets-2.1.1

**Comment by emilyploszaj** [comment]
bannerelytra isn't open source so I can't pr the necessary changes to fix this, I could prevent the crash but then elytra wouldn't render.

**Comment by Devil2548** [comment]
Well, I guess you can do nothing about it, so seeing as this issue is unfix-able, I am just going to close the issue.
